### ISSUE TITLE
Navigating Bootstrap

### ISSUE THREAD

**Issue by amblackburn97** [dh-nuigalway/EN6138-2023#22]
Hi David,

Work Package 4 is struggling with understanding how to use Bootstrap and create/edit the HTML website. Would you have time or office hours next week to teach a few of us how to use it?

Thank you!
Anna Blackburn

**Comment by amblackburn97** [comment]
Hi @davekelly,

Tuesday at 10 would be great. Thanks so much!

**Comment by davekelly** [comment]
Great – I've booked the meeting room on the first floor of the Hardiman Research Building (it's the small glass-walled room before you go through the doors to the "Bridge Room") for 10am on Tuesday.

cc/ @jtonra / @amblackburn97

**Comment by jtonra** [comment]
Many thanks, @davekelly!
