### ISSUE TITLE
Note Colours In EVT

### ISSUE THREAD

**Issue by sineadba** [dh-nuigalway/EN6138-2023#44]
Hi David,
We are struggling to colour code the notes in EVT using CSS, despite using similar code to last year's edition. If possible could you give us advice on what the problem could be? 
Thanks,
WP4

**Comment by davekelly** [comment]
Hi @sineadba 

The file you need to edit with updated CSS rules is: https://github.com/dh-nuigalway/EN6138-2023/blob/main/edition/config/custom-style.css 

Notes in the HTML appear as: 

```
<i class="evt_note ng-scope">
    <span class="etymological"></span>
</i>
```

To target this in CSS you'd need a style rule like:

```
.evt_note .etymological{  /*css rules go in here */ }
```

Let me know if that doesn't work, and I'll take another look...

David

**Comment by sineadba** [comment]
Hi David, 
I tried that code and it doesn't seem to be working. 
Thanks, 
Sinéad

**Comment by davekelly** [comment]
I took a look, and they seem to be working with different colours – is it fixed?

**Comment by ValeriaBarbon** [comment]
Yes we managed to solve the problem! Thank you so much!
